# ---

# - name: Create alias for server
#   lineinfile:
#     path: '/etc/hosts'
#     line: '192.168.20.5 server'

# - name: Install packages
#   apt:
#     pkg:
#      - vim
#     update_cache: yes

# - name: Install Docker
#   apt:
#     name: docker.io
#     state: present
#     update_cache: yes

# - name: Install dependencies for Docker Compose
#   apt:
#     name:
#       - python3-pip
#       - curl
#     state: present

# - name: Install Docker Compose using pip
#   pip:
#     name: docker-compose

# - name: Clone repository from Git
#   git:
#     repo: 'https://github.com/hinhlx/cr_commain_injection.git'
#     dest: /home/user/project
#     version: main

# - name: Build and run Docker Compose
#   shell: docker-compose up --build
#   args:
#     chdir: /home/user/project


# - name: Set root password
#   user:
#     name: root
#     password: "{{ root_password | password_hash('sha512') }}"
# ...
---
  - name: Cập nhật danh sách các gói
  apt:
	update_cache: yes

- name: Cài đặt Apache và PHP
  apt:
	name:
	  - apache2
	  - php
	  - libapache2-mod-php
	  - php-mysql
	state: present

- name: Tạo thư mục cho ứng dụng web
  file:
	path: /var/www/html/commandInjection
	state: directory
	mode: '0755'

- name: Clone mã nguồn từ GitHub
  git:
	repo: 'https://github.com/hinhlx/commandInjection.git' 
	dest: /var/www/html/commandInjection
	version: main
	update: yes

- name: Thiết lập quyền truy cập
  file:
	path: /var/www/html/commandInjection/
	state: directory
	owner: www-data
	group: www-data
	mode: '0755'

- name: Cấu hình Apache để phục vụ ứng dụng
  copy:
	dest: /etc/apache2/sites-available/commandInjection.conf
	content: |
	  <VirtualHost *:80>
		  DocumentRoot /var/www/html/commandInjection
		  <Directory /var/www/html/commandInjection>
			  AllowOverride All
			  Require all granted
		  </Directory>
	  </VirtualHost>

- name: Kích hoạt cấu hình trang web
  shell: |
	a2ensite commandInjection.conf
	a2dissite 000-default.conf
	systemctl reload apache2

- name: Đảm bảo dịch vụ Apache đang chạy
  service:
	name: apache2
	state: started
	enabled: yes
...